const ExternalLinks = {
  golang: 'https://go.dev/',
  labstackEcho: 'https://echo.labstack.com/',
  htmx: 'https://htmx.org/',
  templ: 'https://templ.dev/',
  alpinejs: 'https://alpinejs.dev/',
  nextjs: 'https://nextjs.org/',
  nextApiRoutes: 'https://nextjs.org/docs/pages/building-your-application/routing/api-routes',
  react: 'https://react.dev/',
  node: 'https://nodejs.org/',
  express: 'https://expressjs.com/',
  puppeteer: 'https://pptr.dev/',
  electron: 'https://www.electronjs.org/',
  python: 'https://www.python.org/',
  postgresql: 'https://www.postgresql.org/',
  pgx: 'https://pkg.go.dev/github.com/jackc/pgx/v5',
  cloudflareR2: 'https://www.cloudflare.com/developer-platform/products/r2/',
  cloudflareWorkers: 'https://developers.cloudflare.com/workers/',
  cloudflareImageTransform: 'https://developers.cloudflare.com/images/transform-images/transform-via-workers/',
  r2s3Compatible: 'https://www.cloudflare.com/developer-platform/solutions/s3-compatible-object-storage/',
  netlify: 'https://www.netlify.com/',
  vercel: 'https://vercel.com/',
  dokploy: 'https://dokploy.com/',
  docker: 'https://www.docker.com/',
  nginx: 'https://nginx.org/',
  letsEncrypt: 'https://letsencrypt.org/',
  
  golangDDDBlueprint: 'https://github.com/patrickkdev/go-ddd-blueprint',
  
  spa: 'https://en.wikipedia.org/wiki/Single-page_application',
  ssr: 'https://en.wikipedia.org/wiki/Server-side_scripting#Server-side_rendering',
  seo: 'https://en.wikipedia.org/wiki/Search_engine_optimization',
} as const;

export default ExternalLinks;